[mcp]
[[mcp.servers]]
name = "youtube"              
type = "stdio"    
command = "Python3"                   
args  = ["../MCP_Server/Server.py"]  

[[mcp.servers]]
name = "filesystem"
type = "stdio"
command = "npx"
args = [
  "-y",
  "@modelcontextprotocol/server-filesystem",
  "C:/Users/Gerax/OneDrive/Desktop/UVGG/4-2/Redes/Proyecto"
]

[[mcp.servers]]
name = "git"
type = "stdio"
command = "uvx"
args = ["mcp-server-git"]


[[mcp.servers]]
name = "flavio2"
type = "http"
url = "https://redes-remotemcpserver.fly.dev/mcp"

[[mcp.servers]]
name = "pokemon"
type = "http"
url = "https://redes-proyecto-mcp-673347929287.us-central1.run.app/mcp"
